### PR TITLE
Generate test JSON artifact

### PR DESCRIPTION
**Pull request by calvinnhieu**
- simple script to generate a bite-sized JSON artifact from a real one in S3
- generated artifact stored as a test fixture for unit tests

Relates to #237

### CODE REVIEW

**Comment by calvinnhieu** [comment]
The script generates the test artifact fixture. The input is a real artifact stored in S3. Mainly a helper script to simplify updating the fixture

**Comment by Bento007** [comment]
Then why is the name of the generated file "generated_test_fixture.json" and no "test_fixture.json". The person generating is supposed to rename it?

**Comment by calvinnhieu** [comment]
Ah, was being explicit with the output name. Sure will change to `test_fixture.json`

**Comment by Bento007** [comment]
It wasn't a requirements, but if that is the case you should mention is somewhere so a developer would know to rename it after generating it.

**Pull request merged**
