### PR TITLE
Design for issue #157: Design the file download experience

### PR DESCRIPTION
**Pull request by liaprins-czi**
Fixes https://github.com/HumanCellAtlas/dcp-prototype/issues/157

Here is the prototype for the latest download experience (see issue #157 for some of the requirements it needed to solve for):
https://www.figma.com/proto/aI3bt6MRFJODNnI4q9DGN8/9-Browser?node-id=311%3A4796&viewport=-7247%2C568%2C0.5&scaling=min-zoom

Note that from the first screen you can select a project with several organ-assay-species combinations (at the top) or a project with just one; hovering over project lines in the list of projects reveals the ones you can click on (they turn light blue on hover). Also note that half of the current projects we have only have one organ-assay-species combination.

Please let me know if any parts are ambiguous or need more explanation (i.e. what happens when user takes certain action, etc); I tried to incorporate as many edge cases into this prototype as possible, but I may have missed one.

@colinmegill @calvinnhieu Can you review this from a frontend-feasibility perspective?
@Bento007 @parthshahva Can you review this from a file-serving perspective?
@ambrosejcarr Can you review this from a requirements/acceptance criteria perspective?
Also any other feedback is welcome; just want to make sure I have those ^^^ bases covered.
Thanks!

### CODE REVIEW

**Comment by calvinnhieu** [comment]
Hey Lia, thanks for thinking through and representing as many of the edge cases as you did in the prototype! In particular, I think the project attributes selection is well thought-out since it meets the user where they're probably starting at, with the question "which organ am I interested in? (or species, or attribute)" as opposed entire groupings.

For file type selection, I was wondering if there is a valid download pattern where a user will want a count matrix (csv or mtx) without the cell and/or gene metadata? From the backend's perspective, I had imagined three files be pre-generated and available for download: `.loom` (cell and gene metadata embedded), `.csv.gz` (cell and gene metadata CSVs included in the `gz` archive), `.mtx.gz` (cell and gene metadata CSVs included in the `gz` archive). While this is not a hard requirement, the proposed design would likely require the backend to generate all combinations of `csv.gz`/`mtx.gz` with included metadata per attribute grouping (i.e. 3 matrices per format per grouping). Maybe @ambrosejcarr can provide guidance here.

Also provided context/questions to [file download requirements](https://github.com/HumanCellAtlas/dcp-prototype/issues/157#issuecomment-592775310).

**Comment by liaprins-czi** [comment]
@calvinnhieu Thanks for the feedback, let's see what @ambrosejcarr says about the necessity to separate the count matrices (with exception of .loom) from .csv.gz ... I am pretty sure in past he has said users would want to be able to get them separately, but happy to update if that's changed!

**Comment by ambrosejcarr** [comment]
@calvinnhieu @jahilton has reason to believe users may want the metadata
separately, so we designed it such that you could get the .csv.gz metadata
separate from the .mtx or .csv count matrix data.

**Comment by liaprins-czi** [comment]
Just a reminder:
@colinmegill @calvinnhieu Can you review this from a frontend-feasibility perspective?
@Bento007 @parthshahva Can you review this from a file-serving perspective?
@ambrosejcarr Can you review this from a requirements/acceptance criteria perspective?

Still waiting for review on this PR, as it is important I know if I need to iterate on it further. Thanks!

**Comment by Bento007** [comment]
relates to #50

**Comment by liaprins-czi** [comment]
@Bento007 When you say "I agree that more work will need to be put into the backend to accommodate this download strategy." Do you mean something in my designs, or @ambrosejcarr saying to make the files modular? If the design, more work compared to what other alternative? Thanks!

**Comment by Bento007** [comment]
@liaprins-czi thank you for your question. I was referring to @ambrosejcarr comment.

**Comment by calvinnhieu** [comment]
Looks good from a front-end perspective.

@ambrosejcarr note on modularity is clear - I was confused by the mock using the `.gz` extension on mtx and csv matrix files and csv matrix metadata files. These should be standalone files correct (that have the option to be zipped to a single archive using button on right)?

**Comment by Bento007** [comment]
@liaprins-czi do we need to create tickets for this work?

**Comment by liaprins-czi** [comment]
@Bento007 If you mean for doing the code/implementation part then I woudl think so, but @ambrosejcarr would know more about that.

**Pull request closed without merging**
